### ISSUE TITLE
🫡 기획 & 디자인 수정 사항 반영

### ISSUE THREAD

**Issue by moondev03** [Team-Never-Land/ThinkerBell-Android#9]
## 💼 작업 설명

<br>

## ✅ To-do

- [x] 즐겨찾기 버튼 위치 수정
- [x] 로고 클릭 시 홈으로 이동
- [x] 공지 툴바에서 나의 공지 버튼 제거
- [x] 토스트 라이팅 수정

<br>

## ☁️ Reference

<br>
